### ISSUE TITLE
Jitpack 배포 setup

### ISSUE THREAD

**Issue by welt-bok** [weltcorp/dta-waud-lib-kotlin#3]

**Comment by welt-bok** [comment]
@jeff 
[JitPack](https://jitpack.io/#weltcorp/dta-waud-lib-kotlin)에서 build fail이 발생하였습니다.
![스크린샷 2023-03-24 오후 2 12 35](https://user-images.githubusercontent.com/73510722/227430169-41d472da-38a7-45ee-9b71-e23ff6700e47.png)

[build.log](https://jitpack.io/com/github/weltcorp/dta-waud-lib-kotlin/v1.0.1/build.log) 해결 부탁드릴게요.

**Comment by welt-jeff** [comment]
@welt-bok 

https://github.com/weltcorp/dta-waud-lib-kotlin/commit/ad187cafa7e7754a7f4ae31cc12250073a8c1685

gitignore를 하지 않도록 하여 update하여지만 계속 같은 에러로 build가 되지 않고 있습니다.
제가 gradle, kotlin이 익숙치 않아서 시간이 좀 걸릴것 같습니다!

**Comment by welt-jeff** [comment]
https://jitpack.io/com/github/weltcorp/dta-waud-lib-kotlin/1.0.7/build.log
build 완료 하였습니다.

.gitignore에서 순서에 따라 처리 되는데, !gradle-wrapper.jar이 *.jar보다 위에 있어, ignore처리가 되지 않은 것 같습니다.

!gradle-wrapper.jar을 최하단으로 내려서 해결하였습니다.

**Comment by welt-bok** [comment]
아...네, 고생 많으셨습니다~!!!
